##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Classify structured data with feature columns

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/structured_data/feature_columns">
    <img src="https://www.tensorflow.org/images/tf_logo_32px.png" />
    View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />
    View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

> Warning: The `tf.feature_columns` module described in this tutorial is not recommended for new code. [Keras preprocessing layers](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers) cover this functionality, for migration instructions see the [Migrating feature columns](../../guide/migrate/migrating_feature_columns.ipynb) guide. The `tf.feature_columns` module was designed for use with TF1 `Estimators`. It does fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities.

This tutorial demonstrates how to classify structured data (e.g. tabular data in a CSV). We will use [Keras](https://www.tensorflow.org/guide/keras) to define the model, and `tf.feature_column` as a bridge to map from columns in a CSV to features used to train the model. This tutorial contains complete code to:

* Load a CSV file using [Pandas](https://pandas.pydata.org/).
* Build an input pipeline to batch and shuffle the rows using [tf.data](https://www.tensorflow.org/guide/datasets).
* Map from columns in the CSV to features used to train the model using feature columns.
* Build, train, and evaluate a model using Keras.

## The Dataset

We will use a simplified version of the PetFinder [dataset](https://www.kaggle.com/c/petfinder-adoption-prediction). There are several thousand rows in the CSV. Each row describes a pet, and each column describes an attribute. We will use this information to predict the speed at which the pet will be adopted.

Following is a description of this dataset. Notice there are both numeric and categorical columns. There is a free text column which we will not use in this tutorial.

Column | Description| Feature Type | Data Type
------------|--------------------|----------------------|-----------------
Type | Type of animal (Dog, Cat) | Categorical | string
Age |  Age of the pet | Numerical | integer
Breed1 | Primary breed of the pet | Categorical | string
Color1 | Color 1 of pet | Categorical | string
Color2 | Color 2 of pet | Categorical | string
MaturitySize | Size at maturity | Categorical | string
FurLength | Fur length | Categorical | string
Vaccinated | Pet has been vaccinated | Categorical | string
Sterilized | Pet has been sterilized | Categorical | string
Health | Health Condition | Categorical | string
Fee | Adoption Fee | Numerical | integer
Description | Profile write-up for this pet | Text | string
PhotoAmt | Total uploaded photos for this pet | Numerical | integer
AdoptionSpeed | Speed of adoption | Classification | integer

## Import TensorFlow and other libraries

In [2]:
!pip install sklearn

In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

## Use Pandas to create a dataframe

[Pandas](https://pandas.pydata.org/) is a Python library with many helpful utilities for loading and working with structured data. We will use Pandas to download the dataset from a URL, and load it into a dataframe.

In [4]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

  16384/1668792 [..............................] - ETA: 0s

1671168/1668792 [==============================] - 0s 0us/step


1679360/1668792 [==============================] - 0s 0us/step


In [5]:
dataframe.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

## Create target variable

The task in the original dataset is to predict the speed at which a pet will be adopted (e.g., in the first week, the first month, the first three months, and so on). Let's simplify this for our tutorial. Here, we will transform this into a binary classification problem, and simply predict whether the pet was adopted, or not.

After modifying the label column, 0 will indicate the pet was not adopted, and 1 will indicate it was.

In [6]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

# Drop un-used columns.
dataframe = dataframe.drop(columns=['AdoptionSpeed', 'Description'])

## Split the dataframe into train, validation, and test

The dataset we downloaded was a single CSV file. We will split this into train, validation, and test sets.

In [7]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


## Create an input pipeline using tf.data

Next, we will wrap the dataframes with [tf.data](https://www.tensorflow.org/guide/datasets). This will enable us  to use feature columns as a bridge to map from the columns in the Pandas dataframe to features used to train the model. If we were working with a very large CSV file (so large that it does not fit into memory), we would use tf.data to read it from disk directly. That is not covered in this tutorial.

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Understand the input pipeline

Now that we have created the input pipeline, let's call it to see the format of the data it returns. We have used a small batch size to keep the output readable.

In [10]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Age'])
  print('A batch of targets:', label_batch )

Every feature: ['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize', 'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'PhotoAmt']
A batch of ages: tf.Tensor([ 6  2 36  2  2], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int64)


We can see that the dataset returns a dictionary of column names (from the dataframe) that map to column values from rows in the dataframe.

## Demonstrate several types of feature columns
TensorFlow provides many types of feature columns. In this section, we will create several types of feature columns, and demonstrate how they transform a column from the dataframe.

In [11]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [12]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### Numeric columns
The output of a feature column becomes the input to the model (using the demo function defined above, we will be able to see exactly how each column from the dataframe is transformed). A [numeric column](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column) is the simplest type of column. It is used to represent real valued features. When using this column, your model will receive the column value from the dataframe unchanged.

In [13]:
photo_count = feature_column.numeric_column('PhotoAmt')
demo(photo_count)

[[2.]
 [4.]
 [4.]
 [1.]
 [2.]]


In the PetFinder dataset, most columns from the dataframe are categorical.

### Bucketized columns
Often, you don't want to feed a number directly into the model, but instead split its value into different categories based on numerical ranges. Consider raw data that represents a person's age. Instead of representing age as a numeric column, we could split the age into several buckets using a [bucketized column](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column). Notice the one-hot values below describe which age range each row matches.

In [14]:
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 3, 5])
demo(age_buckets)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


### Categorical columns
In this dataset, Type is represented as a string (e.g. 'Dog', or 'Cat'). We cannot feed strings directly to a model. Instead, we must first map them to numeric values. The categorical vocabulary columns provide a way to represent strings as a one-hot vector (much like you have seen above with age buckets). The vocabulary can be passed as a list using [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list), or loaded from a file using [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file).

In [15]:
animal_type = feature_column.categorical_column_with_vocabulary_list(
      'Type', ['Cat', 'Dog'])

animal_type_one_hot = feature_column.indicator_column(animal_type)
demo(animal_type_one_hot)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]


### Embedding columns
Suppose instead of having just a few possible strings, we have thousands (or more) values per category. For a number of reasons, as the number of categories grow large, it becomes infeasible to train a neural network using one-hot encodings. We can use an embedding column to overcome this limitation. Instead of representing the data as a one-hot vector of many dimensions, an [embedding column](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column) represents that data as a lower-dimensional, dense vector in which each cell can contain any number, not just 0 or 1. The size of the embedding (8, in the example below) is a parameter that must be tuned.

Key point: using an embedding column is best when a categorical column has many possible values. We are using one here for demonstration purposes, so you have a complete example you can modify for a different dataset in the future.

In [16]:
# Notice the input to the embedding column is the categorical column
# we previously created
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
demo(breed1_embedding)

[[-0.22380038 -0.09379731  0.21349265  0.33451992 -0.49730566  0.05174963
   0.2668497   0.27391028]
 [-0.5484653  -0.03492585  0.05648395 -0.09792244  0.02530896 -0.15477926
  -0.10695003 -0.45474145]
 [-0.22380038 -0.09379731  0.21349265  0.33451992 -0.49730566  0.05174963
   0.2668497   0.27391028]
 [ 0.10050306  0.43513173  0.375823    0.5652766   0.40925583 -0.03928828
   0.4901914   0.20637617]
 [-0.2319875  -0.21874283  0.12272807  0.33345345 -0.4563055   0.21609035
  -0.2410521   0.4736915 ]]


### Hashed feature columns

Another way to represent a categorical column with a large number of values is to use a [categorical_column_with_hash_bucket](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket). This feature column calculates a hash value of the input, then selects one of the `hash_bucket_size` buckets to encode a string. When using this column, you do not need to provide the vocabulary, and you can choose to make the number of hash_buckets significantly smaller than the number of actual categories to save space.

Key point: An important downside of this technique is that there may be collisions in which different strings are mapped to the same bucket. In practice, this can work well for some datasets regardless.

In [17]:
breed1_hashed = feature_column.categorical_column_with_hash_bucket(
      'Breed1', hash_bucket_size=10)
demo(feature_column.indicator_column(breed1_hashed))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


### Crossed feature columns
Combining features into a single feature, better known as [feature crosses](https://developers.google.com/machine-learning/glossary/#feature_cross), enables a model to learn separate weights for each combination of features. Here, we will create a new feature that is the cross of Age and Type. Note that `crossed_column` does not build the full table of all possible combinations (which could be very large). Instead, it is backed by a `hashed_column`, so you can choose how large the table is.

In [18]:
crossed_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Choose which columns to use
We have seen how to use several types of feature columns. Now we will use them to train a model. The goal of this tutorial is to show you the complete code (e.g. mechanics) needed to work with feature columns. We have selected a few columns to train our model below arbitrarily.

Key point: If your aim is to build an accurate model, try a larger dataset of your own, and think carefully about which features are the most meaningful to include, and how they should be represented.

In [19]:
feature_columns = []

# numeric cols
for header in ['PhotoAmt', 'Fee', 'Age']:
  feature_columns.append(feature_column.numeric_column(header))

In [20]:
# bucketized cols
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 2, 3, 4, 5])
feature_columns.append(age_buckets)

In [21]:
# indicator_columns
indicator_column_names = ['Type', 'Color1', 'Color2', 'Gender', 'MaturitySize',
                          'FurLength', 'Vaccinated', 'Sterilized', 'Health']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)

In [22]:
# embedding columns
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
feature_columns.append(breed1_embedding)

In [23]:
# crossed columns
age_type_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=100)
feature_columns.append(feature_column.indicator_column(age_type_feature))

### Create a feature layer
Now that we have defined our feature columns, we will use a [DenseFeatures](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures) layer to input them to our Keras model.

In [24]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

Earlier, we used a small batch size to demonstrate how feature columns worked. We create a new input pipeline with a larger batch size.

In [25]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Create, compile, and train the model

In [26]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=10)

Epoch 1/10


  1/231 [..............................] - ETA: 6:26 - loss: 1.0613 - accuracy: 0.4688

  8/231 [>.............................] - ETA: 1s - loss: 0.8654 - accuracy: 0.4102  

 15/231 [>.............................] - ETA: 1s - loss: 0.8801 - accuracy: 0.5437

 23/231 [=>............................] - ETA: 1s - loss: 0.8944 - accuracy: 0.5734

 31/231 [===>..........................] - ETA: 1s - loss: 0.8512 - accuracy: 0.6069

 39/231 [====>.........................] - ETA: 1s - loss: 0.7914 - accuracy: 0.6314

 47/231 [=====>........................] - ETA: 1s - loss: 0.7661 - accuracy: 0.6509

 54/231 [======>.......................] - ETA: 1s - loss: 0.7554 - accuracy: 0.6586

 62/231 [=======>......................] - ETA: 1s - loss: 0.7389 - accuracy: 0.6628

 69/231 [=======>......................] - ETA: 1s - loss: 0.7356 - accuracy: 0.6635

 77/231 [=========>....................] - ETA: 1s - loss: 0.7156 - accuracy: 0.6696

 85/231 [==========>...................] - ETA: 1s - loss: 0.7172 - accuracy: 0.6732

 92/231 [==========>...................] - ETA: 0s - loss: 0.7166 - accuracy: 0.6743

100/231 [===========>..................] - ETA: 0s - loss: 0.7111 - accuracy: 0.6775

108/231 [=============>................] - ETA: 0s - loss: 0.7075 - accuracy: 0.6765

116/231 [==============>...............] - ETA: 0s - loss: 0.7082 - accuracy: 0.6751

123/231 [==============>...............] - ETA: 0s - loss: 0.7035 - accuracy: 0.6728

131/231 [================>.............] - ETA: 0s - loss: 0.6987 - accuracy: 0.6708

138/231 [================>.............] - ETA: 0s - loss: 0.6993 - accuracy: 0.6698

146/231 [=================>............] - ETA: 0s - loss: 0.6975 - accuracy: 0.6725

154/231 [===================>..........] - ETA: 0s - loss: 0.6979 - accuracy: 0.6719

162/231 [====================>.........] - ETA: 0s - loss: 0.6918 - accuracy: 0.6752

170/231 [=====================>........] - ETA: 0s - loss: 0.6891 - accuracy: 0.6779

178/231 [======================>.......] - ETA: 0s - loss: 0.6867 - accuracy: 0.6773

186/231 [=======================>......] - ETA: 0s - loss: 0.6901 - accuracy: 0.6761

194/231 [========================>.....] - ETA: 0s - loss: 0.6859 - accuracy: 0.6769

201/231 [=========================>....] - ETA: 0s - loss: 0.6832 - accuracy: 0.6762

209/231 [==========================>...] - ETA: 0s - loss: 0.6833 - accuracy: 0.6769

217/231 [===========================>..] - ETA: 0s - loss: 0.6811 - accuracy: 0.6789

224/231 [============================>.] - ETA: 0s - loss: 0.6767 - accuracy: 0.6801

231/231 [==============================] - ETA: 0s - loss: 0.6759 - accuracy: 0.6802

231/231 [==============================] - 4s 10ms/step - loss: 0.6759 - accuracy: 0.6802 - val_loss: 0.5361 - val_accuracy: 0.7351


Epoch 2/10


  1/231 [..............................] - ETA: 12s - loss: 0.5595 - accuracy: 0.6562

  8/231 [>.............................] - ETA: 1s - loss: 0.5682 - accuracy: 0.7383 

 15/231 [>.............................] - ETA: 1s - loss: 0.5664 - accuracy: 0.7000

 22/231 [=>............................] - ETA: 1s - loss: 0.5580 - accuracy: 0.7074

 29/231 [==>...........................] - ETA: 1s - loss: 0.5473 - accuracy: 0.7080

 36/231 [===>..........................] - ETA: 1s - loss: 0.5552 - accuracy: 0.7031

 44/231 [====>.........................] - ETA: 1s - loss: 0.5556 - accuracy: 0.7045

 51/231 [=====>........................] - ETA: 1s - loss: 0.5689 - accuracy: 0.7059

 58/231 [======>.......................] - ETA: 1s - loss: 0.5756 - accuracy: 0.7058

 65/231 [=======>......................] - ETA: 1s - loss: 0.5835 - accuracy: 0.7063

 72/231 [========>.....................] - ETA: 1s - loss: 0.5819 - accuracy: 0.6975

 80/231 [=========>....................] - ETA: 1s - loss: 0.5800 - accuracy: 0.6957

 88/231 [==========>...................] - ETA: 1s - loss: 0.5776 - accuracy: 0.6957

 95/231 [===========>..................] - ETA: 0s - loss: 0.5807 - accuracy: 0.6957

103/231 [============>.................] - ETA: 0s - loss: 0.5799 - accuracy: 0.6978

110/231 [=============>................] - ETA: 0s - loss: 0.5766 - accuracy: 0.6986

117/231 [==============>...............] - ETA: 0s - loss: 0.5767 - accuracy: 0.6990

125/231 [===============>..............] - ETA: 0s - loss: 0.5781 - accuracy: 0.7017

132/231 [================>.............] - ETA: 0s - loss: 0.5787 - accuracy: 0.7015

139/231 [=================>............] - ETA: 0s - loss: 0.5828 - accuracy: 0.6990

146/231 [=================>............] - ETA: 0s - loss: 0.5829 - accuracy: 0.7008

153/231 [==================>...........] - ETA: 0s - loss: 0.5798 - accuracy: 0.7030

161/231 [===================>..........] - ETA: 0s - loss: 0.5784 - accuracy: 0.7024

168/231 [====================>.........] - ETA: 0s - loss: 0.5768 - accuracy: 0.7033

176/231 [=====================>........] - ETA: 0s - loss: 0.5735 - accuracy: 0.7044

183/231 [======================>.......] - ETA: 0s - loss: 0.5722 - accuracy: 0.7047

190/231 [=======================>......] - ETA: 0s - loss: 0.5711 - accuracy: 0.7041

197/231 [========================>.....] - ETA: 0s - loss: 0.5712 - accuracy: 0.7049

204/231 [=========================>....] - ETA: 0s - loss: 0.5731 - accuracy: 0.7042

211/231 [==========================>...] - ETA: 0s - loss: 0.5718 - accuracy: 0.7036

218/231 [===========================>..] - ETA: 0s - loss: 0.5728 - accuracy: 0.7051

225/231 [============================>.] - ETA: 0s - loss: 0.5752 - accuracy: 0.7054

231/231 [==============================] - 2s 9ms/step - loss: 0.5742 - accuracy: 0.7054 - val_loss: 0.5178 - val_accuracy: 0.7411


Epoch 3/10


  1/231 [..............................] - ETA: 10s - loss: 0.5052 - accuracy: 0.6562

  8/231 [>.............................] - ETA: 1s - loss: 0.5615 - accuracy: 0.7070 

 15/231 [>.............................] - ETA: 1s - loss: 0.5264 - accuracy: 0.7167

 22/231 [=>............................] - ETA: 1s - loss: 0.5268 - accuracy: 0.7315

 29/231 [==>...........................] - ETA: 1s - loss: 0.5422 - accuracy: 0.7241

 37/231 [===>..........................] - ETA: 1s - loss: 0.5406 - accuracy: 0.7171

 45/231 [====>.........................] - ETA: 1s - loss: 0.5490 - accuracy: 0.7160

 52/231 [=====>........................] - ETA: 1s - loss: 0.5462 - accuracy: 0.7206

 60/231 [======>.......................] - ETA: 1s - loss: 0.5421 - accuracy: 0.7177

 67/231 [=======>......................] - ETA: 1s - loss: 0.5404 - accuracy: 0.7197

 75/231 [========>.....................] - ETA: 1s - loss: 0.5511 - accuracy: 0.7204

 83/231 [=========>....................] - ETA: 1s - loss: 0.5478 - accuracy: 0.7210

 91/231 [==========>...................] - ETA: 0s - loss: 0.5454 - accuracy: 0.7208

 99/231 [===========>..................] - ETA: 0s - loss: 0.5424 - accuracy: 0.7229

107/231 [============>.................] - ETA: 0s - loss: 0.5421 - accuracy: 0.7243

115/231 [=============>................] - ETA: 0s - loss: 0.5428 - accuracy: 0.7245

123/231 [==============>...............] - ETA: 0s - loss: 0.5489 - accuracy: 0.7200

131/231 [================>.............] - ETA: 0s - loss: 0.5507 - accuracy: 0.7161

138/231 [================>.............] - ETA: 0s - loss: 0.5515 - accuracy: 0.7149

146/231 [=================>............] - ETA: 0s - loss: 0.5483 - accuracy: 0.7168

153/231 [==================>...........] - ETA: 0s - loss: 0.5462 - accuracy: 0.7196

161/231 [===================>..........] - ETA: 0s - loss: 0.5445 - accuracy: 0.7211

168/231 [====================>.........] - ETA: 0s - loss: 0.5412 - accuracy: 0.7212

175/231 [=====================>........] - ETA: 0s - loss: 0.5399 - accuracy: 0.7218

182/231 [======================>.......] - ETA: 0s - loss: 0.5368 - accuracy: 0.7237

189/231 [=======================>......] - ETA: 0s - loss: 0.5367 - accuracy: 0.7244

197/231 [========================>.....] - ETA: 0s - loss: 0.5376 - accuracy: 0.7227

204/231 [=========================>....] - ETA: 0s - loss: 0.5375 - accuracy: 0.7232

211/231 [==========================>...] - ETA: 0s - loss: 0.5376 - accuracy: 0.7217

218/231 [===========================>..] - ETA: 0s - loss: 0.5374 - accuracy: 0.7218

225/231 [============================>.] - ETA: 0s - loss: 0.5372 - accuracy: 0.7224

231/231 [==============================] - 2s 9ms/step - loss: 0.5369 - accuracy: 0.7231 - val_loss: 0.5031 - val_accuracy: 0.7438


Epoch 4/10


  1/231 [..............................] - ETA: 11s - loss: 0.5100 - accuracy: 0.6875

  9/231 [>.............................] - ETA: 1s - loss: 0.4681 - accuracy: 0.7292 

 17/231 [=>............................] - ETA: 1s - loss: 0.4564 - accuracy: 0.7390

 24/231 [==>...........................] - ETA: 1s - loss: 0.5164 - accuracy: 0.7214

 32/231 [===>..........................] - ETA: 1s - loss: 0.5139 - accuracy: 0.7129

 40/231 [====>.........................] - ETA: 1s - loss: 0.5157 - accuracy: 0.7031

 48/231 [=====>........................] - ETA: 1s - loss: 0.5155 - accuracy: 0.7116

 55/231 [======>.......................] - ETA: 1s - loss: 0.5243 - accuracy: 0.7091

 63/231 [=======>......................] - ETA: 1s - loss: 0.5238 - accuracy: 0.7054

 71/231 [========>.....................] - ETA: 1s - loss: 0.5244 - accuracy: 0.7099

 78/231 [=========>....................] - ETA: 1s - loss: 0.5271 - accuracy: 0.7055

 86/231 [==========>...................] - ETA: 1s - loss: 0.5277 - accuracy: 0.7035

 93/231 [===========>..................] - ETA: 0s - loss: 0.5251 - accuracy: 0.7056

100/231 [===========>..................] - ETA: 0s - loss: 0.5226 - accuracy: 0.7119

107/231 [============>.................] - ETA: 0s - loss: 0.5240 - accuracy: 0.7094

115/231 [=============>................] - ETA: 0s - loss: 0.5231 - accuracy: 0.7106

122/231 [==============>...............] - ETA: 0s - loss: 0.5203 - accuracy: 0.7144

129/231 [===============>..............] - ETA: 0s - loss: 0.5174 - accuracy: 0.7163

137/231 [================>.............] - ETA: 0s - loss: 0.5183 - accuracy: 0.7185

144/231 [=================>............] - ETA: 0s - loss: 0.5183 - accuracy: 0.7192

152/231 [==================>...........] - ETA: 0s - loss: 0.5190 - accuracy: 0.7200

160/231 [===================>..........] - ETA: 0s - loss: 0.5185 - accuracy: 0.7215

167/231 [====================>.........] - ETA: 0s - loss: 0.5179 - accuracy: 0.7217

174/231 [=====================>........] - ETA: 0s - loss: 0.5163 - accuracy: 0.7232

181/231 [======================>.......] - ETA: 0s - loss: 0.5154 - accuracy: 0.7229

188/231 [=======================>......] - ETA: 0s - loss: 0.5172 - accuracy: 0.7204

195/231 [========================>.....] - ETA: 0s - loss: 0.5147 - accuracy: 0.7213

203/231 [=========================>....] - ETA: 0s - loss: 0.5143 - accuracy: 0.7208

211/231 [==========================>...] - ETA: 0s - loss: 0.5130 - accuracy: 0.7226

218/231 [===========================>..] - ETA: 0s - loss: 0.5165 - accuracy: 0.7210

225/231 [============================>.] - ETA: 0s - loss: 0.5162 - accuracy: 0.7203

231/231 [==============================] - 2s 9ms/step - loss: 0.5161 - accuracy: 0.7214 - val_loss: 0.5115 - val_accuracy: 0.7259


Epoch 5/10


  1/231 [..............................] - ETA: 12s - loss: 0.4113 - accuracy: 0.8125

  8/231 [>.............................] - ETA: 1s - loss: 0.4574 - accuracy: 0.7539 

 15/231 [>.............................] - ETA: 1s - loss: 0.4610 - accuracy: 0.7500

 23/231 [=>............................] - ETA: 1s - loss: 0.4850 - accuracy: 0.7351

 31/231 [===>..........................] - ETA: 1s - loss: 0.4792 - accuracy: 0.7369

 38/231 [===>..........................] - ETA: 1s - loss: 0.4812 - accuracy: 0.7451

 45/231 [====>.........................] - ETA: 1s - loss: 0.4901 - accuracy: 0.7451

 53/231 [=====>........................] - ETA: 1s - loss: 0.4949 - accuracy: 0.7476

 61/231 [======>.......................] - ETA: 1s - loss: 0.4897 - accuracy: 0.7469

 69/231 [=======>......................] - ETA: 1s - loss: 0.4914 - accuracy: 0.7446

 76/231 [========>.....................] - ETA: 1s - loss: 0.4906 - accuracy: 0.7471

 83/231 [=========>....................] - ETA: 1s - loss: 0.4903 - accuracy: 0.7425

 91/231 [==========>...................] - ETA: 1s - loss: 0.4912 - accuracy: 0.7424

 99/231 [===========>..................] - ETA: 0s - loss: 0.4968 - accuracy: 0.7371

107/231 [============>.................] - ETA: 0s - loss: 0.4970 - accuracy: 0.7360

115/231 [=============>................] - ETA: 0s - loss: 0.4991 - accuracy: 0.7345

123/231 [==============>...............] - ETA: 0s - loss: 0.4977 - accuracy: 0.7340

131/231 [================>.............] - ETA: 0s - loss: 0.4988 - accuracy: 0.7345

139/231 [=================>............] - ETA: 0s - loss: 0.5005 - accuracy: 0.7331

147/231 [==================>...........] - ETA: 0s - loss: 0.4993 - accuracy: 0.7353

154/231 [===================>..........] - ETA: 0s - loss: 0.5002 - accuracy: 0.7336

161/231 [===================>..........] - ETA: 0s - loss: 0.5004 - accuracy: 0.7321

169/231 [====================>.........] - ETA: 0s - loss: 0.5021 - accuracy: 0.7313

177/231 [=====================>........] - ETA: 0s - loss: 0.5032 - accuracy: 0.7309

184/231 [======================>.......] - ETA: 0s - loss: 0.5047 - accuracy: 0.7284

191/231 [=======================>......] - ETA: 0s - loss: 0.5044 - accuracy: 0.7281

198/231 [========================>.....] - ETA: 0s - loss: 0.5045 - accuracy: 0.7285

206/231 [=========================>....] - ETA: 0s - loss: 0.5039 - accuracy: 0.7292

213/231 [==========================>...] - ETA: 0s - loss: 0.5043 - accuracy: 0.7283

220/231 [===========================>..] - ETA: 0s - loss: 0.5039 - accuracy: 0.7286

227/231 [============================>.] - ETA: 0s - loss: 0.5038 - accuracy: 0.7294

231/231 [==============================] - 2s 9ms/step - loss: 0.5034 - accuracy: 0.7296 - val_loss: 0.5173 - val_accuracy: 0.7237


Epoch 6/10


  1/231 [..............................] - ETA: 11s - loss: 0.3608 - accuracy: 0.7812

  8/231 [>.............................] - ETA: 1s - loss: 0.4405 - accuracy: 0.7500 

 16/231 [=>............................] - ETA: 1s - loss: 0.4645 - accuracy: 0.7598

 24/231 [==>...........................] - ETA: 1s - loss: 0.4577 - accuracy: 0.7734

 32/231 [===>..........................] - ETA: 1s - loss: 0.4561 - accuracy: 0.7725

 40/231 [====>.........................] - ETA: 1s - loss: 0.4647 - accuracy: 0.7602

 47/231 [=====>........................] - ETA: 1s - loss: 0.4673 - accuracy: 0.7586

 55/231 [======>.......................] - ETA: 1s - loss: 0.4788 - accuracy: 0.7534

 63/231 [=======>......................] - ETA: 1s - loss: 0.4841 - accuracy: 0.7416

 70/231 [========>.....................] - ETA: 1s - loss: 0.4867 - accuracy: 0.7388

 78/231 [=========>....................] - ETA: 1s - loss: 0.4865 - accuracy: 0.7388

 85/231 [==========>...................] - ETA: 1s - loss: 0.4880 - accuracy: 0.7390

 93/231 [===========>..................] - ETA: 0s - loss: 0.4895 - accuracy: 0.7403

101/231 [============>.................] - ETA: 0s - loss: 0.4900 - accuracy: 0.7373

109/231 [=============>................] - ETA: 0s - loss: 0.4927 - accuracy: 0.7374

116/231 [==============>...............] - ETA: 0s - loss: 0.4982 - accuracy: 0.7333

123/231 [==============>...............] - ETA: 0s - loss: 0.4974 - accuracy: 0.7307

130/231 [===============>..............] - ETA: 0s - loss: 0.4992 - accuracy: 0.7300

137/231 [================>.............] - ETA: 0s - loss: 0.4978 - accuracy: 0.7286

145/231 [=================>............] - ETA: 0s - loss: 0.4978 - accuracy: 0.7269

152/231 [==================>...........] - ETA: 0s - loss: 0.4979 - accuracy: 0.7282

160/231 [===================>..........] - ETA: 0s - loss: 0.4966 - accuracy: 0.7287

168/231 [====================>.........] - ETA: 0s - loss: 0.5002 - accuracy: 0.7269

176/231 [=====================>........] - ETA: 0s - loss: 0.4999 - accuracy: 0.7276

184/231 [======================>.......] - ETA: 0s - loss: 0.4984 - accuracy: 0.7288

192/231 [=======================>......] - ETA: 0s - loss: 0.4989 - accuracy: 0.7290

199/231 [========================>.....] - ETA: 0s - loss: 0.4991 - accuracy: 0.7296

206/231 [=========================>....] - ETA: 0s - loss: 0.5002 - accuracy: 0.7291

213/231 [==========================>...] - ETA: 0s - loss: 0.4997 - accuracy: 0.7299

220/231 [===========================>..] - ETA: 0s - loss: 0.4980 - accuracy: 0.7311

227/231 [============================>.] - ETA: 0s - loss: 0.4982 - accuracy: 0.7307

231/231 [==============================] - 2s 8ms/step - loss: 0.4983 - accuracy: 0.7301 - val_loss: 0.5153 - val_accuracy: 0.7254


Epoch 7/10


  1/231 [..............................] - ETA: 11s - loss: 0.3919 - accuracy: 0.9062

  9/231 [>.............................] - ETA: 1s - loss: 0.4794 - accuracy: 0.7639 

 16/231 [=>............................] - ETA: 1s - loss: 0.4718 - accuracy: 0.7656

 24/231 [==>...........................] - ETA: 1s - loss: 0.4750 - accuracy: 0.7565

 32/231 [===>..........................] - ETA: 1s - loss: 0.4784 - accuracy: 0.7490

 40/231 [====>.........................] - ETA: 1s - loss: 0.4833 - accuracy: 0.7398

 48/231 [=====>........................] - ETA: 1s - loss: 0.4867 - accuracy: 0.7428

 55/231 [======>.......................] - ETA: 1s - loss: 0.4931 - accuracy: 0.7312

 62/231 [=======>......................] - ETA: 1s - loss: 0.4885 - accuracy: 0.7379

 70/231 [========>.....................] - ETA: 1s - loss: 0.4902 - accuracy: 0.7348

 78/231 [=========>....................] - ETA: 1s - loss: 0.4893 - accuracy: 0.7376

 85/231 [==========>...................] - ETA: 1s - loss: 0.4883 - accuracy: 0.7382

 93/231 [===========>..................] - ETA: 0s - loss: 0.4920 - accuracy: 0.7382

100/231 [===========>..................] - ETA: 0s - loss: 0.4922 - accuracy: 0.7347

107/231 [============>.................] - ETA: 0s - loss: 0.4923 - accuracy: 0.7360

115/231 [=============>................] - ETA: 0s - loss: 0.4920 - accuracy: 0.7370

123/231 [==============>...............] - ETA: 0s - loss: 0.4919 - accuracy: 0.7373

131/231 [================>.............] - ETA: 0s - loss: 0.4923 - accuracy: 0.7381

139/231 [=================>............] - ETA: 0s - loss: 0.4921 - accuracy: 0.7379

147/231 [==================>...........] - ETA: 0s - loss: 0.4879 - accuracy: 0.7394

154/231 [===================>..........] - ETA: 0s - loss: 0.4917 - accuracy: 0.7370

162/231 [====================>.........] - ETA: 0s - loss: 0.4916 - accuracy: 0.7363

170/231 [=====================>........] - ETA: 0s - loss: 0.4918 - accuracy: 0.7373

177/231 [=====================>........] - ETA: 0s - loss: 0.4912 - accuracy: 0.7380

184/231 [======================>.......] - ETA: 0s - loss: 0.4910 - accuracy: 0.7388

191/231 [=======================>......] - ETA: 0s - loss: 0.4908 - accuracy: 0.7400

199/231 [========================>.....] - ETA: 0s - loss: 0.4895 - accuracy: 0.7404

207/231 [=========================>....] - ETA: 0s - loss: 0.4910 - accuracy: 0.7411

215/231 [==========================>...] - ETA: 0s - loss: 0.4903 - accuracy: 0.7404

223/231 [===========================>..] - ETA: 0s - loss: 0.4900 - accuracy: 0.7406

230/231 [============================>.] - ETA: 0s - loss: 0.4914 - accuracy: 0.7413

231/231 [==============================] - 2s 9ms/step - loss: 0.4912 - accuracy: 0.7412 - val_loss: 0.5258 - val_accuracy: 0.7010


Epoch 8/10


  1/231 [..............................] - ETA: 11s - loss: 0.4749 - accuracy: 0.7188

  8/231 [>.............................] - ETA: 1s - loss: 0.5267 - accuracy: 0.6836 

 16/231 [=>............................] - ETA: 1s - loss: 0.5123 - accuracy: 0.6992

 23/231 [=>............................] - ETA: 1s - loss: 0.5092 - accuracy: 0.7092

 31/231 [===>..........................] - ETA: 1s - loss: 0.5122 - accuracy: 0.6946

 39/231 [====>.........................] - ETA: 1s - loss: 0.5134 - accuracy: 0.6979

 46/231 [====>.........................] - ETA: 1s - loss: 0.5063 - accuracy: 0.7079

 54/231 [======>.......................] - ETA: 1s - loss: 0.5055 - accuracy: 0.7112

 61/231 [======>.......................] - ETA: 1s - loss: 0.4987 - accuracy: 0.7188

 68/231 [=======>......................] - ETA: 1s - loss: 0.4958 - accuracy: 0.7266

 75/231 [========>.....................] - ETA: 1s - loss: 0.4935 - accuracy: 0.7275

 82/231 [=========>....................] - ETA: 1s - loss: 0.4904 - accuracy: 0.7290

 89/231 [==========>...................] - ETA: 1s - loss: 0.4865 - accuracy: 0.7303

 96/231 [===========>..................] - ETA: 0s - loss: 0.4875 - accuracy: 0.7305

104/231 [============>.................] - ETA: 0s - loss: 0.4871 - accuracy: 0.7302

111/231 [=============>................] - ETA: 0s - loss: 0.4865 - accuracy: 0.7328

118/231 [==============>...............] - ETA: 0s - loss: 0.4862 - accuracy: 0.7344

126/231 [===============>..............] - ETA: 0s - loss: 0.4843 - accuracy: 0.7359

134/231 [================>.............] - ETA: 0s - loss: 0.4887 - accuracy: 0.7355

142/231 [=================>............] - ETA: 0s - loss: 0.4899 - accuracy: 0.7355

149/231 [==================>...........] - ETA: 0s - loss: 0.4887 - accuracy: 0.7362

157/231 [===================>..........] - ETA: 0s - loss: 0.4895 - accuracy: 0.7367

164/231 [====================>.........] - ETA: 0s - loss: 0.4928 - accuracy: 0.7369

171/231 [=====================>........] - ETA: 0s - loss: 0.4909 - accuracy: 0.7379

178/231 [======================>.......] - ETA: 0s - loss: 0.4896 - accuracy: 0.7379

185/231 [=======================>......] - ETA: 0s - loss: 0.4898 - accuracy: 0.7373

192/231 [=======================>......] - ETA: 0s - loss: 0.4867 - accuracy: 0.7391

199/231 [========================>.....] - ETA: 0s - loss: 0.4877 - accuracy: 0.7384

206/231 [=========================>....] - ETA: 0s - loss: 0.4859 - accuracy: 0.7407

213/231 [==========================>...] - ETA: 0s - loss: 0.4872 - accuracy: 0.7394

220/231 [===========================>..] - ETA: 0s - loss: 0.4886 - accuracy: 0.7385

228/231 [============================>.] - ETA: 0s - loss: 0.4892 - accuracy: 0.7364

231/231 [==============================] - 2s 9ms/step - loss: 0.4890 - accuracy: 0.7360 - val_loss: 0.5066 - val_accuracy: 0.7221


Epoch 9/10


  1/231 [..............................] - ETA: 11s - loss: 0.7280 - accuracy: 0.5312

  8/231 [>.............................] - ETA: 1s - loss: 0.4661 - accuracy: 0.7227 

 16/231 [=>............................] - ETA: 1s - loss: 0.4532 - accuracy: 0.7500

 23/231 [=>............................] - ETA: 1s - loss: 0.4538 - accuracy: 0.7622

 30/231 [==>...........................] - ETA: 1s - loss: 0.4757 - accuracy: 0.7479

 37/231 [===>..........................] - ETA: 1s - loss: 0.4766 - accuracy: 0.7458

 45/231 [====>.........................] - ETA: 1s - loss: 0.4788 - accuracy: 0.7458

 52/231 [=====>........................] - ETA: 1s - loss: 0.4741 - accuracy: 0.7518

 59/231 [======>.......................] - ETA: 1s - loss: 0.4710 - accuracy: 0.7521

 66/231 [=======>......................] - ETA: 1s - loss: 0.4703 - accuracy: 0.7505

 73/231 [========>.....................] - ETA: 1s - loss: 0.4710 - accuracy: 0.7517

 80/231 [=========>....................] - ETA: 1s - loss: 0.4725 - accuracy: 0.7535

 87/231 [==========>...................] - ETA: 1s - loss: 0.4775 - accuracy: 0.7525

 95/231 [===========>..................] - ETA: 0s - loss: 0.4803 - accuracy: 0.7477

102/231 [============>.................] - ETA: 0s - loss: 0.4770 - accuracy: 0.7515

109/231 [=============>................] - ETA: 0s - loss: 0.4781 - accuracy: 0.7514

116/231 [==============>...............] - ETA: 0s - loss: 0.4809 - accuracy: 0.7508

123/231 [==============>...............] - ETA: 0s - loss: 0.4807 - accuracy: 0.7492

130/231 [===============>..............] - ETA: 0s - loss: 0.4832 - accuracy: 0.7469

138/231 [================>.............] - ETA: 0s - loss: 0.4821 - accuracy: 0.7498

145/231 [=================>............] - ETA: 0s - loss: 0.4848 - accuracy: 0.7461

152/231 [==================>...........] - ETA: 0s - loss: 0.4862 - accuracy: 0.7440

160/231 [===================>..........] - ETA: 0s - loss: 0.4861 - accuracy: 0.7434

168/231 [====================>.........] - ETA: 0s - loss: 0.4853 - accuracy: 0.7433

175/231 [=====================>........] - ETA: 0s - loss: 0.4849 - accuracy: 0.7420

182/231 [======================>.......] - ETA: 0s - loss: 0.4831 - accuracy: 0.7442

189/231 [=======================>......] - ETA: 0s - loss: 0.4818 - accuracy: 0.7452

196/231 [========================>.....] - ETA: 0s - loss: 0.4825 - accuracy: 0.7449

203/231 [=========================>....] - ETA: 0s - loss: 0.4834 - accuracy: 0.7457

210/231 [==========================>...] - ETA: 0s - loss: 0.4825 - accuracy: 0.7464

217/231 [===========================>..] - ETA: 0s - loss: 0.4820 - accuracy: 0.7457

225/231 [============================>.] - ETA: 0s - loss: 0.4827 - accuracy: 0.7447

231/231 [==============================] - 2s 9ms/step - loss: 0.4824 - accuracy: 0.7443 - val_loss: 0.5091 - val_accuracy: 0.7481


Epoch 10/10


  1/231 [..............................] - ETA: 11s - loss: 0.4127 - accuracy: 0.7500

  8/231 [>.............................] - ETA: 1s - loss: 0.4805 - accuracy: 0.7461 

 16/231 [=>............................] - ETA: 1s - loss: 0.4897 - accuracy: 0.7559

 23/231 [=>............................] - ETA: 1s - loss: 0.5013 - accuracy: 0.7323

 30/231 [==>...........................] - ETA: 1s - loss: 0.4949 - accuracy: 0.7323

 37/231 [===>..........................] - ETA: 1s - loss: 0.4738 - accuracy: 0.7407

 45/231 [====>.........................] - ETA: 1s - loss: 0.4739 - accuracy: 0.7444

 52/231 [=====>........................] - ETA: 1s - loss: 0.4706 - accuracy: 0.7494

 59/231 [======>.......................] - ETA: 1s - loss: 0.4758 - accuracy: 0.7436

 67/231 [=======>......................] - ETA: 1s - loss: 0.4747 - accuracy: 0.7439

 74/231 [========>.....................] - ETA: 1s - loss: 0.4699 - accuracy: 0.7479

 82/231 [=========>....................] - ETA: 1s - loss: 0.4683 - accuracy: 0.7511

 89/231 [==========>...................] - ETA: 1s - loss: 0.4666 - accuracy: 0.7507

 96/231 [===========>..................] - ETA: 0s - loss: 0.4665 - accuracy: 0.7474

103/231 [============>.................] - ETA: 0s - loss: 0.4659 - accuracy: 0.7521

111/231 [=============>................] - ETA: 0s - loss: 0.4650 - accuracy: 0.7517

119/231 [==============>...............] - ETA: 0s - loss: 0.4676 - accuracy: 0.7513

126/231 [===============>..............] - ETA: 0s - loss: 0.4698 - accuracy: 0.7500

133/231 [================>.............] - ETA: 0s - loss: 0.4744 - accuracy: 0.7472

141/231 [=================>............] - ETA: 0s - loss: 0.4763 - accuracy: 0.7431

148/231 [==================>...........] - ETA: 0s - loss: 0.4747 - accuracy: 0.7439

155/231 [===================>..........] - ETA: 0s - loss: 0.4742 - accuracy: 0.7452

163/231 [====================>.........] - ETA: 0s - loss: 0.4751 - accuracy: 0.7465

171/231 [=====================>........] - ETA: 0s - loss: 0.4760 - accuracy: 0.7454

179/231 [======================>.......] - ETA: 0s - loss: 0.4760 - accuracy: 0.7456

187/231 [=======================>......] - ETA: 0s - loss: 0.4794 - accuracy: 0.7435

194/231 [========================>.....] - ETA: 0s - loss: 0.4788 - accuracy: 0.7447

201/231 [=========================>....] - ETA: 0s - loss: 0.4791 - accuracy: 0.7446

208/231 [==========================>...] - ETA: 0s - loss: 0.4789 - accuracy: 0.7452

216/231 [===========================>..] - ETA: 0s - loss: 0.4781 - accuracy: 0.7454

224/231 [============================>.] - ETA: 0s - loss: 0.4765 - accuracy: 0.7461

231/231 [==============================] - ETA: 0s - loss: 0.4758 - accuracy: 0.7466

231/231 [==============================] - 2s 9ms/step - loss: 0.4758 - accuracy: 0.7466 - val_loss: 0.5159 - val_accuracy: 0.7492


In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

 1/73 [..............................] - ETA: 1s - loss: 0.2954 - accuracy: 0.8750

10/73 [===>..........................] - ETA: 0s - loss: 0.5254 - accuracy: 0.7406

19/73 [======>.......................] - ETA: 0s - loss: 0.5075 - accuracy: 0.7368

28/73 [==========>...................] - ETA: 0s - loss: 0.5056 - accuracy: 0.7467

37/73 [==============>...............] - ETA: 0s - loss: 0.5063 - accuracy: 0.7416

45/73 [=================>............] - ETA: 0s - loss: 0.5022 - accuracy: 0.7396

54/73 [=====================>........] - ETA: 0s - loss: 0.4924 - accuracy: 0.7436

63/73 [========================>.....] - ETA: 0s - loss: 0.4901 - accuracy: 0.7490

71/73 [============================>.] - ETA: 0s - loss: 0.4817 - accuracy: 0.7531

73/73 [==============================] - 0s 6ms/step - loss: 0.4812 - accuracy: 0.7543


Accuracy 0.7543327808380127


Key point: You will typically see best results with deep learning with much larger and more complex datasets. When working with a small dataset like this one, we recommend using a decision tree or random forest as a strong baseline. The goal of this tutorial is not to train an accurate model, but to demonstrate the mechanics of working with structured data, so you have code to use as a starting point when working with your own datasets in the future.

## Next steps
The best way to learn more about classifying structured data is to try it yourself. We suggest finding another dataset to work with, and training a model to classify it using code similar to the above. To improve accuracy, think carefully about which features to include in your model, and how they should be represented.